server:
    port: 8081
spring:
    datasource:
        password: password
        url: jdbc:mysql://localhost:3306/book_borrow_db?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                
# Test Details for Development Environment
test:
  details: Book Borrow service details for development environment [From GitHub]
  Place: Ireland
  department: Development Testing [Book service]
  placeContact:
    name: Dublin
    phone: 123-456-7890                
